version: '3.8'

services:
  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
    restart: always
    
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    restart: always

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: always